/**
 * Events the admin controller emits and the admin console pages/modals
 * listen for. One SUCCESS/FAILURE pair per gateway call — named after the
 * gateway function it wraps so the two are never hard to match up.
 */
export const ADMIN_EVENTS = {
  // Users
  GET_ALL_USERS_SUCCESS: 'ADMIN_GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'ADMIN_GET_ALL_USERS_FAILURE',
  GET_USER_CREDITS_SUCCESS: 'ADMIN_GET_USER_CREDITS_SUCCESS',
  GET_USER_CREDITS_FAILURE: 'ADMIN_GET_USER_CREDITS_FAILURE',
  GET_USER_DETAILS_SUCCESS: 'ADMIN_GET_USER_DETAILS_SUCCESS',
  GET_USER_DETAILS_FAILURE: 'ADMIN_GET_USER_DETAILS_FAILURE',

  // Credits
  UPDATE_CREDITS_SUCCESS: 'ADMIN_UPDATE_CREDITS_SUCCESS',
  UPDATE_CREDITS_FAILURE: 'ADMIN_UPDATE_CREDITS_FAILURE',

  // Analytics / Insights
  GET_ANALYTICS_OVERVIEW_SUCCESS: 'ADMIN_GET_ANALYTICS_OVERVIEW_SUCCESS',
  GET_ANALYTICS_OVERVIEW_FAILURE: 'ADMIN_GET_ANALYTICS_OVERVIEW_FAILURE',
  GET_USER_USAGE_ANALYTICS_SUCCESS: 'ADMIN_GET_USER_USAGE_ANALYTICS_SUCCESS',
  GET_USER_USAGE_ANALYTICS_FAILURE: 'ADMIN_GET_USER_USAGE_ANALYTICS_FAILURE',
  GET_USER_DAILY_ACTIVITY_SUCCESS: 'ADMIN_GET_USER_DAILY_ACTIVITY_SUCCESS',
  GET_USER_DAILY_ACTIVITY_FAILURE: 'ADMIN_GET_USER_DAILY_ACTIVITY_FAILURE',

  // Transactions
  GET_TRANSACTIONS_SUCCESS: 'ADMIN_GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILURE: 'ADMIN_GET_TRANSACTIONS_FAILURE',

  // Action costs (Pricing)
  GET_ACTION_COSTS_SUCCESS: 'ADMIN_GET_ACTION_COSTS_SUCCESS',
  GET_ACTION_COSTS_FAILURE: 'ADMIN_GET_ACTION_COSTS_FAILURE',
  UPDATE_ACTION_COST_SUCCESS: 'ADMIN_UPDATE_ACTION_COST_SUCCESS',
  UPDATE_ACTION_COST_FAILURE: 'ADMIN_UPDATE_ACTION_COST_FAILURE',
  UPDATE_ACTION_BILLING_SUCCESS: 'ADMIN_UPDATE_ACTION_BILLING_SUCCESS',
  UPDATE_ACTION_BILLING_FAILURE: 'ADMIN_UPDATE_ACTION_BILLING_FAILURE',

  // Plans
  GET_PLANS_SUCCESS: 'ADMIN_GET_PLANS_SUCCESS',
  GET_PLANS_FAILURE: 'ADMIN_GET_PLANS_FAILURE',
  CREATE_PLAN_SUCCESS: 'ADMIN_CREATE_PLAN_SUCCESS',
  CREATE_PLAN_FAILURE: 'ADMIN_CREATE_PLAN_FAILURE',
  UPDATE_PLAN_SUCCESS: 'ADMIN_UPDATE_PLAN_SUCCESS',
  UPDATE_PLAN_FAILURE: 'ADMIN_UPDATE_PLAN_FAILURE',
  ASSIGN_USER_PLAN_SUCCESS: 'ADMIN_ASSIGN_USER_PLAN_SUCCESS',
  ASSIGN_USER_PLAN_FAILURE: 'ADMIN_ASSIGN_USER_PLAN_FAILURE',

  // Promo codes
  GET_PROMO_CODES_SUCCESS: 'ADMIN_GET_PROMO_CODES_SUCCESS',
  GET_PROMO_CODES_FAILURE: 'ADMIN_GET_PROMO_CODES_FAILURE',
  CREATE_PROMO_CODE_SUCCESS: 'ADMIN_CREATE_PROMO_CODE_SUCCESS',
  CREATE_PROMO_CODE_FAILURE: 'ADMIN_CREATE_PROMO_CODE_FAILURE',
  UPDATE_PROMO_CODE_SUCCESS: 'ADMIN_UPDATE_PROMO_CODE_SUCCESS',
  UPDATE_PROMO_CODE_FAILURE: 'ADMIN_UPDATE_PROMO_CODE_FAILURE',
  DELETE_PROMO_CODE_SUCCESS: 'ADMIN_DELETE_PROMO_CODE_SUCCESS',
  DELETE_PROMO_CODE_FAILURE: 'ADMIN_DELETE_PROMO_CODE_FAILURE',

  // Billing exemptions
  GET_BILLING_EXEMPTIONS_SUCCESS: 'ADMIN_GET_BILLING_EXEMPTIONS_SUCCESS',
  GET_BILLING_EXEMPTIONS_FAILURE: 'ADMIN_GET_BILLING_EXEMPTIONS_FAILURE',
  GRANT_BILLING_EXEMPTION_SUCCESS: 'ADMIN_GRANT_BILLING_EXEMPTION_SUCCESS',
  GRANT_BILLING_EXEMPTION_FAILURE: 'ADMIN_GRANT_BILLING_EXEMPTION_FAILURE',
  REVOKE_BILLING_EXEMPTION_SUCCESS: 'ADMIN_REVOKE_BILLING_EXEMPTION_SUCCESS',
  REVOKE_BILLING_EXEMPTION_FAILURE: 'ADMIN_REVOKE_BILLING_EXEMPTION_FAILURE',

  // Hub entitlement
  GET_HUB_ACCOUNTS_SUCCESS: 'ADMIN_GET_HUB_ACCOUNTS_SUCCESS',
  GET_HUB_ACCOUNTS_FAILURE: 'ADMIN_GET_HUB_ACCOUNTS_FAILURE',
  GRANT_HUB_ACCESS_SUCCESS: 'ADMIN_GRANT_HUB_ACCESS_SUCCESS',
  GRANT_HUB_ACCESS_FAILURE: 'ADMIN_GRANT_HUB_ACCESS_FAILURE',
  REVOKE_HUB_ACCESS_SUCCESS: 'ADMIN_REVOKE_HUB_ACCESS_SUCCESS',
  REVOKE_HUB_ACCESS_FAILURE: 'ADMIN_REVOKE_HUB_ACCESS_FAILURE',
  GET_UNOWNED_HUB_ACCOUNTS_SUCCESS: 'ADMIN_GET_UNOWNED_HUB_ACCOUNTS_SUCCESS',
  GET_UNOWNED_HUB_ACCOUNTS_FAILURE: 'ADMIN_GET_UNOWNED_HUB_ACCOUNTS_FAILURE',
  BIND_HUB_ACCOUNT_SUCCESS: 'ADMIN_BIND_HUB_ACCOUNT_SUCCESS',
  BIND_HUB_ACCOUNT_FAILURE: 'ADMIN_BIND_HUB_ACCOUNT_FAILURE',

  // Payments (read-only)
  GET_PAYMENTS_SUCCESS: 'ADMIN_GET_PAYMENTS_SUCCESS',
  GET_PAYMENTS_FAILURE: 'ADMIN_GET_PAYMENTS_FAILURE',
  GET_USER_PAYMENTS_SUCCESS: 'ADMIN_GET_USER_PAYMENTS_SUCCESS',
  GET_USER_PAYMENTS_FAILURE: 'ADMIN_GET_USER_PAYMENTS_FAILURE',
};
