/**
 * Subscription/billing module events, dispatched by the controller and
 * subscribed to by SubscriptionContext and the pages that trigger these
 * actions directly (SubscribePage).
 */
export const SUBSCRIPTION_EVENTS = {
  GET_PRICING_SUCCESS: 'SUBSCRIPTION_GET_PRICING_SUCCESS',
  GET_PRICING_FAILURE: 'SUBSCRIPTION_GET_PRICING_FAILURE',

  VALIDATE_PROMO_SUCCESS: 'SUBSCRIPTION_VALIDATE_PROMO_SUCCESS',
  VALIDATE_PROMO_FAILURE: 'SUBSCRIPTION_VALIDATE_PROMO_FAILURE',

  CREATE_SUBSCRIPTION_SUCCESS: 'SUBSCRIPTION_CREATE_SUBSCRIPTION_SUCCESS',
  CREATE_SUBSCRIPTION_FAILURE: 'SUBSCRIPTION_CREATE_SUBSCRIPTION_FAILURE',

  GET_MY_SUBSCRIPTION_SUCCESS: 'SUBSCRIPTION_GET_MY_SUBSCRIPTION_SUCCESS',
  GET_MY_SUBSCRIPTION_FAILURE: 'SUBSCRIPTION_GET_MY_SUBSCRIPTION_FAILURE',
};
