export const PAGE_SIZE = 50;
export const POLL_MS = 5000;

export const LEAD_EVENTS = {
  CREATE_SEARCH_SUCCESS: 'LEAD_CREATE_SEARCH_SUCCESS',
  CREATE_SEARCH_FAILURE: 'LEAD_CREATE_SEARCH_FAILURE',
  SEARCH_AUDIENCE_PARAMS_SUCCESS: 'LEAD_SEARCH_AUDIENCE_PARAMS_SUCCESS',
  SEARCH_AUDIENCE_PARAMS_FAILURE: 'LEAD_SEARCH_AUDIENCE_PARAMS_FAILURE',
  LIST_SEARCHES_SUCCESS: 'LEAD_LIST_SEARCHES_SUCCESS',
  LIST_SEARCHES_FAILURE: 'LEAD_LIST_SEARCHES_FAILURE',
  GET_SEARCH_SUCCESS: 'LEAD_GET_SEARCH_SUCCESS',
  GET_SEARCH_FAILURE: 'LEAD_GET_SEARCH_FAILURE',
  RUN_SEARCH_SUCCESS: 'LEAD_RUN_SEARCH_SUCCESS',
  RUN_SEARCH_FAILURE: 'LEAD_RUN_SEARCH_FAILURE',
  DELETE_SEARCH_SUCCESS: 'LEAD_DELETE_SEARCH_SUCCESS',
  DELETE_SEARCH_FAILURE: 'LEAD_DELETE_SEARCH_FAILURE',
  LIST_LEADS_SUCCESS: 'LEAD_LIST_LEADS_SUCCESS',
  LIST_LEADS_FAILURE: 'LEAD_LIST_LEADS_FAILURE',
  RESOLVE_PROFILE_SUCCESS: 'LEAD_RESOLVE_PROFILE_SUCCESS',
  RESOLVE_PROFILE_FAILURE: 'LEAD_RESOLVE_PROFILE_FAILURE',
  WITHDRAW_INVITATION_SUCCESS: 'LEAD_WITHDRAW_INVITATION_SUCCESS',
  WITHDRAW_INVITATION_FAILURE: 'LEAD_WITHDRAW_INVITATION_FAILURE',
  CREATE_LIST_SUCCESS: 'LEAD_CREATE_LIST_SUCCESS',
  CREATE_LIST_FAILURE: 'LEAD_CREATE_LIST_FAILURE',
  ADD_TO_AUDIENCE_SUCCESS: 'LEAD_ADD_TO_AUDIENCE_SUCCESS',
  ADD_TO_AUDIENCE_FAILURE: 'LEAD_ADD_TO_AUDIENCE_FAILURE',
  REMOVE_FROM_AUDIENCE_SUCCESS: 'LEAD_REMOVE_FROM_AUDIENCE_SUCCESS',
  REMOVE_FROM_AUDIENCE_FAILURE: 'LEAD_REMOVE_FROM_AUDIENCE_FAILURE',
  SOURCING_USAGE_SUCCESS: 'LEAD_SOURCING_USAGE_SUCCESS',
  SOURCING_USAGE_FAILURE: 'LEAD_SOURCING_USAGE_FAILURE',
  FOLLOWER_SOURCES_SUCCESS: 'LEAD_FOLLOWER_SOURCES_SUCCESS',
  FOLLOWER_SOURCES_FAILURE: 'LEAD_FOLLOWER_SOURCES_FAILURE',
};

/** Default "profiles to fetch" — the old fixed import size. */
export const DEFAULT_FETCH_COUNT = 30;

/** Default "followers to import" — bigger than a search's: a follower list is cheap to page and the audience is usually the point. */
export const DEFAULT_FOLLOWERS_COUNT = 100;

/** Options for the table's "Last activity" type filter (server param `activityType`). */
export const ACTIVITY_TYPES = [
  { value: 'invite', label: 'Invite sent' },
  { value: 'message', label: 'Message sent' },
  { value: 'imported', label: 'Imported' },
  { value: 'enriched', label: 'Enriched' },
];
