/** Poll interval while the network is syncing. */
export const POLL_MS = 5000;

export const PAGE_SIZE = 50;

export const NETWORK_EVENTS = {
  GET_NETWORK_SUCCESS: 'NETWORK_GET_NETWORK_SUCCESS',
  GET_NETWORK_FAILURE: 'NETWORK_GET_NETWORK_FAILURE',
  SYNC_NETWORK_SUCCESS: 'NETWORK_SYNC_NETWORK_SUCCESS',
  SYNC_NETWORK_FAILURE: 'NETWORK_SYNC_NETWORK_FAILURE',
  LIST_CONNECTIONS_SUCCESS: 'NETWORK_LIST_CONNECTIONS_SUCCESS',
  LIST_CONNECTIONS_FAILURE: 'NETWORK_LIST_CONNECTIONS_FAILURE',
};
