/**
 * Poll interval while anything in this feature is live (a running campaign,
 * an in-progress send). 10s: sending is measured in a handful an hour, so
 * anything faster is a lot of requests to watch a number that barely moves.
 *
 * One constant, not one per hook — useCampaigns.js and useCampaignDetail.js
 * both poll on this same cadence and used to each define their own copy of
 * the same number.
 */
export const POLL_MS = 10000;

export const CAMPAIGN_EVENTS = {
  CREATE_CAMPAIGN_SUCCESS: 'CAMPAIGN_CREATE_CAMPAIGN_SUCCESS',
  CREATE_CAMPAIGN_FAILURE: 'CAMPAIGN_CREATE_CAMPAIGN_FAILURE',
  LIST_CAMPAIGNS_SUCCESS: 'CAMPAIGN_LIST_CAMPAIGNS_SUCCESS',
  LIST_CAMPAIGNS_FAILURE: 'CAMPAIGN_LIST_CAMPAIGNS_FAILURE',
  GET_CAMPAIGN_SUCCESS: 'CAMPAIGN_GET_CAMPAIGN_SUCCESS',
  GET_CAMPAIGN_FAILURE: 'CAMPAIGN_GET_CAMPAIGN_FAILURE',
  LIST_MEMBERS_SUCCESS: 'CAMPAIGN_LIST_MEMBERS_SUCCESS',
  LIST_MEMBERS_FAILURE: 'CAMPAIGN_LIST_MEMBERS_FAILURE',
  ADD_LEADS_SUCCESS: 'CAMPAIGN_ADD_LEADS_SUCCESS',
  ADD_LEADS_FAILURE: 'CAMPAIGN_ADD_LEADS_FAILURE',
  UPDATE_CAMPAIGN_SUCCESS: 'CAMPAIGN_UPDATE_CAMPAIGN_SUCCESS',
  UPDATE_CAMPAIGN_FAILURE: 'CAMPAIGN_UPDATE_CAMPAIGN_FAILURE',
  START_CAMPAIGN_SUCCESS: 'CAMPAIGN_START_CAMPAIGN_SUCCESS',
  START_CAMPAIGN_FAILURE: 'CAMPAIGN_START_CAMPAIGN_FAILURE',
  PAUSE_CAMPAIGN_SUCCESS: 'CAMPAIGN_PAUSE_CAMPAIGN_SUCCESS',
  PAUSE_CAMPAIGN_FAILURE: 'CAMPAIGN_PAUSE_CAMPAIGN_FAILURE',
  RETRY_FAILED_SUCCESS: 'CAMPAIGN_RETRY_FAILED_SUCCESS',
  RETRY_FAILED_FAILURE: 'CAMPAIGN_RETRY_FAILED_FAILURE',
  DELETE_CAMPAIGN_SUCCESS: 'CAMPAIGN_DELETE_CAMPAIGN_SUCCESS',
  DELETE_CAMPAIGN_FAILURE: 'CAMPAIGN_DELETE_CAMPAIGN_FAILURE',
};
