/**
 * Poll interval while a sequence is live: the list poll (while any sequence
 * is running) and the detail-page poll (while that one sequence is
 * running) both used this same number before this file existed.
 */
export const POLL_MS = 10000;

/**
 * Events the sequences controller emits and the sequences hooks/pages
 * listen for.
 */
export const SEQUENCE_EVENTS = {
  CREATE_SEQUENCE_SUCCESS: 'SEQUENCE_CREATE_SEQUENCE_SUCCESS',
  CREATE_SEQUENCE_FAILURE: 'SEQUENCE_CREATE_SEQUENCE_FAILURE',
  LIST_SEQUENCES_SUCCESS: 'SEQUENCE_LIST_SEQUENCES_SUCCESS',
  LIST_SEQUENCES_FAILURE: 'SEQUENCE_LIST_SEQUENCES_FAILURE',
  GET_SEQUENCE_SUCCESS: 'SEQUENCE_GET_SEQUENCE_SUCCESS',
  GET_SEQUENCE_FAILURE: 'SEQUENCE_GET_SEQUENCE_FAILURE',
  UPDATE_SEQUENCE_SUCCESS: 'SEQUENCE_UPDATE_SEQUENCE_SUCCESS',
  UPDATE_SEQUENCE_FAILURE: 'SEQUENCE_UPDATE_SEQUENCE_FAILURE',
  LIST_ENROLLMENTS_SUCCESS: 'SEQUENCE_LIST_ENROLLMENTS_SUCCESS',
  LIST_ENROLLMENTS_FAILURE: 'SEQUENCE_LIST_ENROLLMENTS_FAILURE',
  ENROLL_LEADS_SUCCESS: 'SEQUENCE_ENROLL_LEADS_SUCCESS',
  ENROLL_LEADS_FAILURE: 'SEQUENCE_ENROLL_LEADS_FAILURE',
  START_SEQUENCE_SUCCESS: 'SEQUENCE_START_SEQUENCE_SUCCESS',
  START_SEQUENCE_FAILURE: 'SEQUENCE_START_SEQUENCE_FAILURE',
  PAUSE_SEQUENCE_SUCCESS: 'SEQUENCE_PAUSE_SEQUENCE_SUCCESS',
  PAUSE_SEQUENCE_FAILURE: 'SEQUENCE_PAUSE_SEQUENCE_FAILURE',
  DELETE_SEQUENCE_SUCCESS: 'SEQUENCE_DELETE_SEQUENCE_SUCCESS',
  DELETE_SEQUENCE_FAILURE: 'SEQUENCE_DELETE_SEQUENCE_FAILURE',
};
