export const INVITATION_TABS = [
  { id: 'sent', label: 'Sent' },
  { id: 'received', label: 'Received' },
  { id: 'rules', label: 'Rules' },
];

export const INVITATIONS_EVENTS = {
  GET_SENT_SUCCESS: 'INVITATIONS_GET_SENT_SUCCESS',
  GET_SENT_FAILURE: 'INVITATIONS_GET_SENT_FAILURE',
  WITHDRAW_SUCCESS: 'INVITATIONS_WITHDRAW_SUCCESS',
  WITHDRAW_FAILURE: 'INVITATIONS_WITHDRAW_FAILURE',
  GET_RECEIVED_SUCCESS: 'INVITATIONS_GET_RECEIVED_SUCCESS',
  GET_RECEIVED_FAILURE: 'INVITATIONS_GET_RECEIVED_FAILURE',
  RESPOND_SUCCESS: 'INVITATIONS_RESPOND_SUCCESS',
  RESPOND_FAILURE: 'INVITATIONS_RESPOND_FAILURE',
  GET_RULES_SUCCESS: 'INVITATIONS_GET_RULES_SUCCESS',
  GET_RULES_FAILURE: 'INVITATIONS_GET_RULES_FAILURE',
  SAVE_RULES_SUCCESS: 'INVITATIONS_SAVE_RULES_SUCCESS',
  SAVE_RULES_FAILURE: 'INVITATIONS_SAVE_RULES_FAILURE',
  GET_USAGE_SUCCESS: 'INVITATIONS_GET_USAGE_SUCCESS',
  GET_USAGE_FAILURE: 'INVITATIONS_GET_USAGE_FAILURE',
  FOLLOW_SUCCESS: 'INVITATIONS_FOLLOW_SUCCESS',
  FOLLOW_FAILURE: 'INVITATIONS_FOLLOW_FAILURE',
  SKILLS_SUCCESS: 'INVITATIONS_SKILLS_SUCCESS',
  SKILLS_FAILURE: 'INVITATIONS_SKILLS_FAILURE',
  ENDORSE_SUCCESS: 'INVITATIONS_ENDORSE_SUCCESS',
  ENDORSE_FAILURE: 'INVITATIONS_ENDORSE_FAILURE',
};

export const DEFAULT_RULES = {
  autoWithdraw: { enabled: false, afterDays: 21 },
  autoAccept: { enabled: false, acceptAll: false, headlineKeywords: [] },
  lastRunAt: null,
  lastRun: null,
};

export const WITHDRAW_DAYS = { min: 7, max: 90 };
