export const companyStrings = {
  back: 'LinkedIn settings',
  loadingTitle: 'Company',
  refresh: 'Refresh',
  openOnLinkedIn: 'Open on LinkedIn',
  manage: 'You manage this page',
  about: 'About',
  locations: 'Locations',
  headquarters: 'Headquarters',
  noAbout: 'This company has not written an about section.',
  notFoundTitle: 'Company not found',
  notFoundBody: 'LinkedIn has no company with that name or id for your account.',
  noAccountTitle: 'Connect your LinkedIn account first',
  noAccountBody: 'Company details come from your connected LinkedIn account.',
  noAccountCta: 'Open LinkedIn settings',
  errorTitle: 'Could not load this company',
  errorBody: 'LinkedIn did not answer. Try again in a moment.',
  retry: 'Try again',
  tiles: { followers: 'Followers', employees: 'Employees', founded: 'Founded', industry: 'Industry' },
  fresh: (when) => `Saved ${when}. Refreshes on its own every 7 days.`,
};
