/** Staging table page size. */
export const DEFAULT_LIMIT = 50;

/** Events the import controller emits and the import hooks/pages listen for. */
export const IMPORT_EVENTS = {
  IMPORT_SUCCESS: 'IMPORT_IMPORT_SUCCESS',
  IMPORT_FAILURE: 'IMPORT_IMPORT_FAILURE',
  LOAD_SUCCESS: 'IMPORT_LOAD_SUCCESS',
  LOAD_FAILURE: 'IMPORT_LOAD_FAILURE',
  PROMOTE_SUCCESS: 'IMPORT_PROMOTE_SUCCESS',
  PROMOTE_FAILURE: 'IMPORT_PROMOTE_FAILURE',
  DELETE_SUCCESS: 'IMPORT_DELETE_SUCCESS',
  DELETE_FAILURE: 'IMPORT_DELETE_FAILURE',
  RETRY_SUCCESS: 'IMPORT_RETRY_SUCCESS',
  RETRY_FAILURE: 'IMPORT_RETRY_FAILURE',
};
