export const viewersStrings = {
  pageTitle: 'Profile viewers',
  pageSubtitle: 'Who looked at your LinkedIn profile, newest first. Spurly keeps the ones it has seen, so the list outlives LinkedIn\'s short window.',
  syncNow: 'Sync now',
  emptyTitle: 'No viewers stored yet',
  emptyHint: 'Press Sync now and Spurly reads who has viewed your profile. After that it checks again on its own.',
  noMatchTitle: 'No viewers with this connection level',
  noMatchHint: 'Try a different filter.',
  accountTitle: 'Connect your LinkedIn account first',
  accountBody: 'Reading profile viewers needs a working LinkedIn connection.',
  accountCta: 'Open LinkedIn settings',
  limitedTitle: 'LinkedIn shows free accounts only 3 viewers',
  limitedBody: 'Premium shows the full list. Everything LinkedIn does show you is saved here.',
  rejected: 'LinkedIn changed something on their side, so profile viewers cannot be read right now. This usually fixes itself within days. The viewers saved earlier are still here.',
  failed: 'The last check did not finish. The viewers saved earlier are still here.',
  privateTitle: 'Private viewers',
  privateBody: 'These people browse in private mode, so LinkedIn hides who they are. Showing the latest check.',
  tiles: {
    last7d: 'Last 7 days',
    last30d: 'Last 30 days',
    stored: 'Viewers saved',
    private: 'Private viewers',
    never: 'Never',
  },
  tileCaptions: {
    last7d: 'Named viewers',
    last30d: 'Named viewers',
    stored: 'Everyone Spurly has seen',
    private: 'In the latest check',
  },
  columns: { viewer: 'Viewer', degree: 'Deg', lastViewed: 'Last viewed', timesSeen: 'Times seen' },
  footnote: 'LinkedIn only gives a rough age ("Viewed 5h ago"), so every time here is approximate. Viewers are checked every 12 hours on Premium accounts.',
};
