export const networkStrings = {
  pageTitle: 'Network',
  pageSubtitle: 'Everyone you are connected to on LinkedIn, kept up to date in the background.',
  syncFirst: 'Sync my connections',
  syncNow: 'Check for new connections',
  emptyTitle: 'Your connections are not here yet',
  emptyHint: 'Sync once and Spurly pulls in everyone you are connected to, then keeps the list current. You can leave the page while it runs.',
  noMatchTitle: 'No connections match',
  noMatchHint: 'Try a different name.',
  working: 'Pulling in your connections · you can leave the page',
  searchPlaceholder: 'Search your connections',
  failed: 'The last sync did not finish. Press "Check for new connections" to try again.',
  accountTitle: 'Connect your LinkedIn account first',
  accountBody: 'Syncing needs a working LinkedIn connection.',
  accountCta: 'Open LinkedIn settings',
  footnote: 'Title and company appear after a connection is enriched. Connections you remove on LinkedIn are not detected yet.',
  tiles: {
    connections: 'Connections',
    lastChecked: 'Last checked',
    nextCheck: 'Next check',
    never: 'Never',
    soon: 'Soon',
  },
};
