/**
 * Reads src/products/pages/website/content/**.md and writes two generated
 * modules next to them:
 *
 *   content.meta.generated.js    frontmatter only (paths, titles, dates, faq...).
 *                                Small and plain ESM, so seo.js can import it from
 *                                Node (prerender, sitemap) and routes.jsx can build
 *                                its <Route>s without pulling every page body in.
 *   content.bodies.generated.js  { [path]: blocks }, loaded only by the lazy
 *                                ContentPage chunk.
 *
 * Runs from npm's predev / prebuild / pretest hooks (and from the Vite dev server
 * when a .md changes). Files with `draft: true` are validated but left out.
 * Fails loudly on a malformed file or a duplicate path.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseContentFile } from './contentParser.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const CONTENT_DIR = path.join(ROOT, 'src/products/pages/website/content');

function mdFiles(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) return mdFiles(full);
    return e.name.endsWith('.md') && e.name.toLowerCase() !== 'readme.md' ? [full] : [];
  });
}

export function buildContent({ dir = CONTENT_DIR, quiet = false } = {}) {
  const pages = [];
  const seen = new Map();
  for (const file of mdFiles(dir).sort()) {
    const rel = path.relative(ROOT, file);
    const { meta, body } = parseContentFile(fs.readFileSync(file, 'utf8'), rel);
    if (seen.has(meta.path)) throw new Error(`${rel}: path ${meta.path} is already used by ${seen.get(meta.path)}`);
    seen.set(meta.path, rel);
    if (meta.seoTitle && meta.seoTitle.length > 60) console.warn(`[content] ${rel}: seoTitle is ${meta.seoTitle.length} chars (aim for <= 60)`);
    if (meta.description.length > 155) console.warn(`[content] ${rel}: description is ${meta.description.length} chars (aim for <= 155)`);
    const { todo = [], ...publicMeta } = meta; // open questions for the author: reported here, never shipped
    for (const t of [].concat(todo)) console.warn(`[content] TODO ${meta.path}: ${t}`);
    if (meta.draft) continue;
    pages.push({ meta: publicMeta, body });
  }
  pages.sort((a, b) => a.meta.path.localeCompare(b.meta.path));

  const banner = '/* GENERATED by scripts/buildContent.mjs from the .md files under content/. Do not edit; run `npm run content`. */\n';
  const metaJs = `${banner}export const CONTENT_META = ${JSON.stringify(pages.map((p) => p.meta), null, 2)};\n`;
  const bodies = Object.fromEntries(pages.map((p) => [p.meta.path, p.body]));
  const bodiesJs = `${banner}export const CONTENT_BODIES = ${JSON.stringify(bodies)};\n`;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'content.meta.generated.js'), metaJs);
  fs.writeFileSync(path.join(dir, 'content.bodies.generated.js'), bodiesJs);
  if (!quiet) console.log(`[content] ${pages.length} pages (${seen.size - pages.length} drafts skipped)`);
  return pages;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) buildContent();
