export const invitationsStrings = {
  pageTitle: 'Invitations',
  pageSubtitle: 'Connection requests you sent and ones waiting for you, read live from LinkedIn.',
  refresh: 'Refresh',
  tabs: { sent: 'Sent', received: 'Received', rules: 'Rules' },
  accountTitle: 'Connect your LinkedIn account first',
  accountBody: 'Invitations are read from your LinkedIn account, so it needs a working connection.',
  accountCta: 'Open LinkedIn settings',
  usage: {
    withdraw: 'Withdrawn in the last 24 h',
    respond: 'Answered in the last 24 h',
  },
  sent: {
    emptyTitle: 'No pending invitations',
    emptyHint: 'Every request you sent has been answered or withdrawn.',
    failed: 'Could not read your sent invitations. Try Refresh.',
    withdraw: 'Withdraw',
    stale: 'Stale',
    staleTitle: (days) => `Pending ${days} days or more`,
    footnote: 'Only requests still waiting are listed. LinkedIn may block inviting the same person again for about three weeks after a withdrawal.',
    columns: { person: 'Person', sent: 'Sent', note: 'Note' },
    age: (days) => (days === null || days === undefined ? 'Unknown' : days === 0 ? 'Today' : days === 1 ? '1 day ago' : `${days} days ago`),
  },
  received: {
    emptyTitle: 'No invitations waiting',
    emptyHint: 'When someone invites you, it shows up here.',
    failed: 'Could not read your incoming invitations. Try Refresh.',
    accept: 'Accept',
    decline: 'Decline',
    notActionable: 'LinkedIn did not give Spurly what it needs to answer this one. Answer it on LinkedIn.',
    footnote: 'Answers are sent from your account and counted toward a daily limit to keep it safe.',
    columns: { person: 'Person', message: 'Message', received: 'Received' },
  },
  loadMore: 'Load more',
  rules: {
    title: 'Automations',
    intro: 'Both are off until you switch them on. Each action goes through the same daily limits as everything else Spurly does for you.',
    withdrawTitle: 'Withdraw stale invitations',
    withdrawHint: 'Withdraws requests that have been pending too long.',
    afterDays: 'Withdraw after (days)',
    acceptTitle: 'Accept incoming invitations',
    acceptHint: 'Accepts invitations that match, and leaves the rest for you.',
    acceptAll: 'Accept everyone',
    acceptAllHint: 'Ignores the keywords below. Use with care.',
    keywords: 'Headline keywords',
    keywordsPlaceholder: 'founder, cto, head of growth',
    keywordsHint: 'Separate with commas. A match anywhere in their headline counts.',
    needKeywords: 'Add at least one keyword, or switch on "Accept everyone".',
    daysRange: 'Choose a whole number of days from 7 to 90.',
    save: 'Save rules',
    lastRun: (when, withdrawn, accepted) => `Last run ${when}: ${withdrawn} withdrawn, ${accepted} accepted.`,
    lastRunStopped: (reason) => `It stopped early because of a limit (${reason}).`,
    lastRunError: 'The last run did not finish.',
    runsNote: 'Runs a couple of times an hour, only on accounts with a rule switched on.',
  },
  capReasons: {
    'daily-cap': 'daily limit',
    'hourly-cap': 'hourly limit',
    'too-soon': 'pacing',
    'outside-hours': 'outside working hours',
  },
};
