/**
 * Poll interval while an enrichment campaign is still running.
 *
 * Shorter than campaigns' 10s: a single enrichment resolve is a couple of
 * seconds to tens of seconds (sourcing/service.js), not the "a handful an
 * hour" pace of a paced outreach send, so a batch of even 20-30 leads is
 * usually done inside a minute or two and a slower poll would make the page
 * feel stuck.
 */
export const POLL_MS = 4000;

export const ENRICHMENT_EVENTS = {
  CREATE_ENRICHMENT_CAMPAIGN_SUCCESS: 'ENRICHMENT_CREATE_ENRICHMENT_CAMPAIGN_SUCCESS',
  CREATE_ENRICHMENT_CAMPAIGN_FAILURE: 'ENRICHMENT_CREATE_ENRICHMENT_CAMPAIGN_FAILURE',
  LIST_ENRICHMENT_CAMPAIGNS_SUCCESS: 'ENRICHMENT_LIST_ENRICHMENT_CAMPAIGNS_SUCCESS',
  LIST_ENRICHMENT_CAMPAIGNS_FAILURE: 'ENRICHMENT_LIST_ENRICHMENT_CAMPAIGNS_FAILURE',
  GET_ENRICHMENT_CAMPAIGN_SUCCESS: 'ENRICHMENT_GET_ENRICHMENT_CAMPAIGN_SUCCESS',
  GET_ENRICHMENT_CAMPAIGN_FAILURE: 'ENRICHMENT_GET_ENRICHMENT_CAMPAIGN_FAILURE',
  LIST_LEADS_SUCCESS: 'ENRICHMENT_LIST_LEADS_SUCCESS',
  LIST_LEADS_FAILURE: 'ENRICHMENT_LIST_LEADS_FAILURE',
  RETRY_FAILED_SUCCESS: 'ENRICHMENT_RETRY_FAILED_SUCCESS',
  RETRY_FAILED_FAILURE: 'ENRICHMENT_RETRY_FAILED_FAILURE',
  DELETE_ENRICHMENT_CAMPAIGN_SUCCESS: 'ENRICHMENT_DELETE_ENRICHMENT_CAMPAIGN_SUCCESS',
  DELETE_ENRICHMENT_CAMPAIGN_FAILURE: 'ENRICHMENT_DELETE_ENRICHMENT_CAMPAIGN_FAILURE',
};
