export const discoverStrings = {
  pageTitle: 'Discover',
  pageSubtitle: 'Find companies that fit, who is hiring, and who is posting about it. Then pull the people in.',
  usageLabel: (used, cap) => `${used} of ${cap} searches used today`,
  accountTitle: 'Connect your LinkedIn account first',
  accountBody: 'Searching LinkedIn needs a working LinkedIn connection.',
  accountCta: 'Open LinkedIn settings',
  lockedTitle: 'Your LinkedIn account does not include this search',
  lockedBody: 'LinkedIn did not let this account run it. Companies and people search keep working.',
  cappedTitle: 'You have used today\'s searches',
  cappedBody: 'The daily limit protects your LinkedIn account. It resets at midnight UTC.',
  rateLimited: 'LinkedIn is limiting searches right now. Wait a few minutes.',
  failedBody: 'That search did not finish. Try again.',
  tabs: {
    companies: {
      keywordsLabel: 'Company keywords',
      keywordsPlaceholder: 'e.g. fintech, B2B SaaS, solar installers',
      urlPlaceholder: 'https://www.linkedin.com/search/results/companies/?keywords=…',
      emptyTitle: 'Search for companies',
      emptyHint: 'Type what the company does. Then open it, or find the people who work there.',
      noResultsTitle: 'No companies found',
      noResultsHint: 'Try different keywords.',
    },
    jobs: {
      keywordsLabel: 'Job keywords',
      keywordsPlaceholder: 'e.g. react developer, head of sales',
      urlPlaceholder: 'https://www.linkedin.com/jobs/search/?keywords=…',
      emptyTitle: 'Search for jobs',
      emptyHint: 'A company hiring is a reason to reach out. Results are grouped by company.',
      noResultsTitle: 'No jobs found',
      noResultsHint: 'Try different keywords.',
    },
    posts: {
      keywordsLabel: 'Post keywords',
      keywordsPlaceholder: 'e.g. hiring react, looking for a CRM',
      urlPlaceholder: 'https://www.linkedin.com/search/results/content/?keywords=…',
      emptyTitle: 'Search for posts',
      emptyHint: 'People who post about a topic care about it. Select the authors you want and import them.',
      noResultsTitle: 'No posts found',
      noResultsHint: 'Try different keywords or a longer time range.',
    },
  },
  search: 'Search',
  searching: 'Searching LinkedIn',
  pasteUrl: 'Paste a LinkedIn search URL instead',
  useKeywords: 'Use keywords instead',
  urlLabel: 'LinkedIn search URL',
  loadMore: 'Load more',
  resultsTotal: (n) => `${n.toLocaleString()} results on LinkedIn`,
  noMoreResults: 'That is everything LinkedIn returned for this search.',
  company: {
    openCompany: 'Open company',
    findPeople: 'Find people here',
    school: 'School',
    showSchools: 'Show schools',
    hideSchools: 'Hide schools',
    followers: (n) => `${n} followers`,
    schoolNote: 'Schools have no company page to search people in.',
  },
  jobs: {
    roles: (n) => (n === 1 ? '1 role' : `${n} roles`),
    noCompany: 'Company not shown by LinkedIn',
    promoted: 'Promoted',
    easyApply: 'Easy Apply',
    moreRoles: (n) => `+${n} more`,
    openJob: 'View on LinkedIn',
  },
  posts: {
    selectAll: 'Select all on this page',
    selected: (n) => `${n} selected`,
    importAuthors: 'Import authors',
    importing: 'Importing',
    companyAuthor: 'Company page',
    companyAuthorNote: 'Company pages cannot be imported as people.',
    reactions: (n) => `${n} reactions`,
    comments: (n) => `${n} comments`,
    hiring: 'Hiring post',
    note: 'Importing counts each person against your daily and monthly profile fetches. They arrive without a title or company until enriched.',
    importedTitle: (n) => (n === 1 ? 'Imported 1 new person' : `Imported ${n} new people`),
    importedBody: (had, skipped) => [
      had > 0 ? `${had} ${had === 1 ? 'was' : 'were'} already in your leads and ${had === 1 ? 'was' : 'were'} added to the audience.` : '',
      skipped > 0 ? `${skipped} skipped (company pages or repeats).` : '',
    ].filter(Boolean).join(' '),
    openLeads: 'Open Leads',
    tooMany: (max) => `Select at most ${max} authors at a time.`,
  },
};
